spring:
  application:
    name: microservice-provider-user
  profiles:
    active: a1
eureka:
  client:
    service-url:
    #用户名：user,密码：123123，对应server配置
      defaultZone: http://user:123123@localhost:8091/eureka
  instance:
    prefer-ip-address: true


---
spring:
  profiles: a1
server:
  port: 8092

---
spring:
  profiles: a2
server:
  port: 8093