server:
  port: 8082
spring:
  application:
    name: microservice-provider-user
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
  instance:
    prefer-ip-address: true