server:
  port: 8082
spring:
  application:
    name: microservice-provider-user
eureka:
  client:
    service-url:
    #用户名：user,密码：123123，对应server配置
      defaultZone: http://user:123123@localhost:8081/eureka
  instance:
    prefer-ip-address: true